# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[package]
authors = ["thegecko <github@thegecko.org>"]
edition = "2021"
name = "node-usb-rs"
version = "0.1.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
# Default enable napi4 feature, see https://nodejs.org/api/n-api.html#node-api-version-matrix
napi = { version = "2.2.0", default-features = false, features = ["napi4"] }
napi-derive = "2.2.0"
rusb = "0.9"

[build-dependencies]
napi-build = "1.2.1"

[profile.release]
lto = true
